services:
  client:
    build: ./client
    env_file:
      - .env.prod
    depends_on:
      - server
    
  server:
    build: ./server
    ports:
      - 5001:5001
    depends_on: 
      postgres:
        condition: service_healthy
    env_file:
      - .env.prod
    command: 
      - sh
      - -c
      - "npx sequelize-cli@latest db:migrate && npm start"
    restart: on-failure
    stdin_open: true
    tty: true

  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env.prod
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/:/etc/nginx/certs
    depends_on:
      - client
      - server

volumes:
  postgres-data: