version: '3.8'

services:
  server:
    build: ./server
    ports:
      - 5001:5001
    depends_on: 
      postgres:
        condition: service_healthy
    command: 
      - sh
      - -c
      - "npx sequelize-cli@latest db:migrate && npm start"
    restart: on-failure
    stdin_open: true
    tty: true

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: